export default [
  {
    id: "1",
    name: "SaNaSa",
    address: "Džemala Bijedića 26",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service A", "Service B", "Service C"],
    doctors: ["Dr. John Doe", "Dr. Jane Smith", "Dr. David Johnson"],
  },
  {
    id: "2",
    name: "Interlab",
    address: "Hamdije Kreševljakovića 19",
    phone: "061111722",
    email: "labmail2@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "3",
    name: "LabEx",
    address: "Titova 1",
    phone: "061111722",
    email: "labmail3@gmail.com",
    services: ["Service P", "Service Q", "Service R"],
    doctors: [
      "Dr. Christopher Taylor",
      "Dr. Sophia Martinez",
      "Dr. Samuel Anderson",
    ],
  },
  {
    id: "4",
    name: "LabPlus",
    address: "Obala Kulina Bana 9",
    phone: "061111722",
    email: "labmail4@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "5",
    name: "MediLab",
    address: "Zmaja od Bosne 8",
    phone: "061111722",
    email: "labmail5@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "6",
    name: "BioLab",
    address: "Kralja Tvrtka 15",
    phone: "061111722",
    email: "labmail6@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "7",
    name: "ZdravoLab",
    address: "Pofalići 10",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "8",
    name: "LabPoint",
    address: "Titova 45",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "9",
    name: "CityLab",
    address: "Safvet-bega Bašagića 27",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "10",
    name: "LabExpert",
    address: "Franjevaca 8",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "11",
    name: "LabMedic",
    address: "Marsala Tita 11",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "12",
    name: "LabNova",
    address: "Zmaja od Bosne 16",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "13",
    name: "MegaLab",
    address: "Titova 32",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "14",
    name: "DermLab",
    address: "Hamdije Ćemerlića 2",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "15",
    name: "MedLab24",
    address: "Bistrik 5",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "16",
    name: "LabCentar",
    address: "Aleja Bosne Srebrene 3",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "17",
    name: "LabVita",
    address: "Hamdije Čemerlića 12",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "18",
    name: "LabClinic",
    address: "Džemala Bijedića 55",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "19",
    name: "LabTest",
    address: "Titova 21",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
  {
    id: "20",
    name: "Eurofarm",
    address: "Grbavicka 20",
    phone: "061111722",
    email: "labmail1@gmail.com",
    services: ["Service X", "Service Y", "Service Z"],
    doctors: ["Dr. Michael Brown", "Dr. Emily Davis", "Dr. Olivia Wilson"],
  },
];
